# .github/workflows/ai-pm.yml
name: AI-Powered Project Management

on:
  push:
    branches:
      - main
    paths:
      - 'requirements.md'

permissions:
  contents: read # requirements.md を読み込むため

jobs:
  generate_tasks_and_milestones:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install requests PyGithub

      - name: Install GitHub CLI
        run: |
          # GitHub CLI を手動でインストールするコマンド (最新版を確実にインストール)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_FOR_PM }} # 環境変数としてトークンを設定

      - name: Run AI-powered Project Item Generator
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # GitHub APIへの認証にPATを使用（secrets.GH_PAT_FOR_PMをGITHUB_TOKENとして渡す）
          GITHUB_TOKEN: ${{ secrets.GH_PAT_FOR_PM }} 
          GITHUB_ORG_NAME: ${{ github.repository_owner }}
          FRONTEND_REPO_NAME: "GITRIS-frontend"
          BACKEND_REPO_NAME: "GITRIS-backend"
          GITHUB_PROJECT_NAME: "GITRIS"
        run: |
          # gh CLI に明示的にログインする
          # GITHUB_TOKEN環境変数があれば自動的に認証されますが、
          # 環境によっては明示的なログインが必要な場合があるため再追加します。
          # 警告で終了コード1が返されるのを防ぐため || true を追加。
          echo "$GITHUB_TOKEN" | gh auth login --with-token || true
          
          # ログイン状態を確認（デバッグ用。成功していれば'Logged in to github.com'と表示）
          gh auth status 

          # その後、Pythonスクリプトを実行
          python scripts/generate_project_items.py requirements.md
