# .github/workflows/ai-pm.yml
name: AI-Powered Project Management

on:
  push:
    branches:
      - main
    paths:
      - 'requirements.md'

# ここでpermissionsセクションを削除するか、read権限のみに絞る
# なぜなら、Issue/マイルストーンの作成はPATで行い、GITHUB_TOKENの権限は最小限にするため
permissions:
  contents: read # requirements.md を読み込むため
  # issues: write, pull-requests: write, repository-projects: write などは削除
  # これらの書き込み権限はPATで提供するため、GITHUB_TOKENには不要

jobs:
  generate_tasks_and_milestones:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install requests PyGithub

      - name: Install GitHub CLI
        # 修正: 'cli/cli/setup-gh@v0' から 'actions/setup-gh@v2' へ変更
        uses: actions/setup-gh@v2
        with:
          version: 'latest'
        env:
          # gh CLI の認証にもPATを使用
          GITHUB_TOKEN: ${{ secrets.GH_PAT_FOR_PM }}

      - name: Run AI-powered Project Item Generator
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # GitHub APIへの認証にPATを使用
          GITHUB_TOKEN: ${{ secrets.GH_PAT_FOR_PM }} # ここをPATのSecret名に変更
          GITHUB_ORG_NAME: ${{ github.repository_owner }}
          FRONTEND_REPO_NAME: "GITRIS-frontend" # あなたのフロントエンドリポジトリ名
          BACKEND_REPO_NAME: "GITRIS-backend"   # あなたのバックエンドリポジトリ名
          GITHUB_PROJECT_NAME: "GITRIS Development Board" # あなたのGitHub Project名
        run: |
          python scripts/generate_project_items.py requirements.md
